name = "LabelledSystem"
version = "0.1.0"
defaultTargets = ["LabelledSystem"]
description = "Labelled Systems for Modal Logic"

[[lean_lib]]
name = "LabelledSystem"

[[lean_exe]]
name = "modaltableau"
root = "Main"

[[require]]
name = "foundation"
scope = "FormalizedFormalLogic"
version = "git#master"

[leanOptions]
linter.flexible = true
